### ISSUE TITLE
Material design 3

### ISSUE THREAD

**Issue by ManuTheCoder** [materializecss/materialize#233] opened 2021-12-19 00:18 UTC
Hey everyone, 
A new version of Material Design has been released. Currently, no other framework has this implemented. This would make Materializecss more different, and popular if you guys would update all components to the new specs.

Here's the link for the new specs:  [https://m3.material.io](https://m3.material.io)

**Comment by ChildishGiant** [comment] 2021-12-19 21:35
Duplicate of #216

**Closed by ChildishGiant** 2021-12-19 21:35 UTC
