### ISSUE TITLE
Select Component does not have onChange Event

### ISSUE THREAD

**Issue by Memiin** [materializecss/materialize#61] opened 2021-01-05 01:04 UTC
I was doing a filter using a multiple select, checking the documentation I realize that there is no **onChange** like callback

![imagen](https://user-images.githubusercontent.com/6427644/103594734-27e57000-4ebf-11eb-8ec0-615770324ebf.png)

## Expected Behavior
The component should have a built-in callback that triggers whenever the user changes the selected item.

## Current Behavior
There is no way to trigger the onChange event on the component

## Possible Solution
I alredy fixed this, creating the callback in the select component, works for both multiple and regular select.

## Context
I needed to filter some items using the selectedItems in the select  component but I found that there is no callback currently

**Comment by Smankusors** [comment] 2021-01-05 05:42
> The component should have a built-in callback that triggers whenever the user changes the selected item.

why? Isn't it already built in on current browser implementations? There's no need to reimplement this AFAIK. 💭

**Comment by Memiin** [comment] 2021-01-05 07:03
@Smankusors well, when you init the select it changes to an UL and the options become Li, but there is no handy way to get the onchange Event

**Comment by Smankusors** [comment] 2021-01-05 08:10
> @Smankusors well, when you init the select it changes to an UL and the options become Li, but there is no handy way to get the onchange Event

it didn't. When you init, the materialize will prepend the `ul` element and hide the actual `select` element. Check your DevTools again.

**Comment by DanielRuf** [comment] 2021-01-14 17:10
So is this a bug report, intended behavior or a feature / change request?

**Comment by Smankusors** [comment] 2021-01-14 17:33
> So is this a bug report, intended behavior or a feature / change request?

hmm the way I see, this is the intended behavior.

**Comment by DanielRuf** [comment] 2021-01-14 20:20
I see it similar. I would say this is an edge case that was not needed so far.

Can you share your solution with us so others can use it too @Memiin? That would be awesome.
I think we can close this as this is not an issue and a very special edge case.

**Comment by Memiin** [comment] 2021-01-14 20:26
> 
> 
> I see it similar. I would say this is an edge case that was not needed so far.
> 
> Can you share your solution with us so others can use it too @Memiin? That would be awesome.
> I think we can close this as this is not an issue and a very special edge case.

I would be happy to share my fix, just a question I´m new to this, should I just make the pull request? or is there something else i  have to do first?

**Comment by DanielRuf** [comment] 2021-01-14 20:57
> I would be happy to share my fix, just a question I´m new to this, should I just make the pull request? or is there something else i have to do first?

A PR would be helpful and sufficient.

**Comment by DanielRuf** [comment] 2021-01-14 20:58
> I would be happy to share my fix, just a question I´m new to this, should I just make the pull request? or is there something else i have to do first?

A PR would be very helpful and sufficient.

**Comment by DanielRuf** [comment] 2021-01-14 20:58
> I would be happy to share my fix, just a question I´m new to this, should I just make the pull request? or is there something else i have to do first?

A PR would be very helpful and is sufficient.

**Comment by wuda-io** [comment] 2021-03-08 21:53
I also think it is **intended behavoir**. You can add the onChange Event on the Select Element directly. The

**Closed by wuda-io** 2021-03-08 21:53 UTC
Labels: component: select
