### ISSUE TITLE
Dropdown wrong item click on ios14 (only when closeOnClick is true)

### ISSUE THREAD

**Issue by nipmarsh** [materializecss/materialize#58] opened 2020-12-12 11:19 UTC
When clicking on a dropdown item on ios14, the wrong one is clicked.
I set the timeouts to 200 in _handleDocumentClick for a test and this solve the problem

**Comment by ChildishGiant** [comment] 2021-01-11 21:31
Is this not a duplicate of #31?

**Comment by Smankusors** [comment] 2021-01-12 08:27
> Isn't this a duplicate of #31?

hmm... yeah there's similiarity with that. Except with different solution, @nipmarsh using timeout, while @nekonenene using ontouchend

**Comment by nipmarsh** [comment] 2021-01-12 10:00
@ChildishGiant yes indeed this seems to be

**Comment by wuda-io** [comment] 2021-09-24 09:28
https://github.com/materializecss/materialize/pull/195

**Closed by wuda-io** 2021-09-24 09:28 UTC
Labels: component: dropdown, iOS only
