### ISSUE TITLE
samples at https://materializeweb.com/getting-started.html broken

### ISSUE THREAD

**Issue by iozuniga** [materializecss/materialize#489] opened 2024-07-05 17:21 UTC
This links do not work:

- https://materializeweb.com/templates/starter-template/preview.html
- https://materializeweb.com/templates/parallax-template/preview.html

TIA. Regards,

**Comment by gselderslaghs** [comment] 2024-11-04 13:11
Duplicate of #492

**Closed** 2024-11-05 00:56 UTC
Labels: documentation
